.TH REMASTERSYS 1 "April 10, 2012" 
.SH NAME
respin-gtk \- official gui for respin
.SH SYNOPSIS
sudo respin-gtk 
.br
.br
 
.SH DESCRIPTION
Respin is a script used to make a bootable live cd or dvd from an
installed Ubuntu system or derivative. This is the gui.
.PP
This manual page documents
.BR respin .
.B respin
Makes a live cd or dvd iso file from and installed system

Makes system backup minus the user folders.
.SH AUTHOR
Marcia Wilbur - Copyright (c) 2014,2015
.SH BUG REPORT
Report bugs to aicra@faqlinux.com
.SH URL
http://www.linuxrespin.com

